server:
  port: 8082
logging:
  level:
    root: INFO
    com:
      leyou: DEBUG
  file: ./logs/upload.log
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 10MB # 限制文件上传的大小
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
fdfs:
  so-timeout: 2500
  connect-timeout: 600
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 10.45.50.241:22122
