server:
  port: 8088
spring:
  application:
    name: comments-service
  datasource:
    url: jdbc:mysql://10.45.50.241:3306/leyou
    username: leyou
    password: leyou
  rabbitmq:
      virtual-host: /
      username: admin
      password: admin
      host: 10.45.50.241
  redis:
    host: 10.45.50.241
  jackson:
    default-property-inclusion: non_null # 配置json处理时忽略空值
logging:
  level:
    root: INFO
    com:
      leyou: DEBUG
  file: ./logs/comments.log
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
leyou:
  jwt:
    #pubKeyPath: H:/javacode/idea/rsa/rsa.pub # 公钥地址
    pubKeyPath: /leyou/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN
