server:
  port: 10012
spring:
  application:
    name: turbine
logging:
  level:
    root: INFO
    com:
      leyou: DEBUG

  file: ./logs/turbine.log
eureka:
  client:
    service-url:
      defaultZone: http://10.45.50.241:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ##ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
turbine:
  aggregator:
    cluster-config: default
  app-config: AUTH-SERVICE
  cluster-name-expression: new String("default")


