server:
  port: 8086
logging:
  level:
    root: INFO
    com:
      leyou: DEBUG
  file: ./logs/sms.log
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 10.45.50.241
    username: admin
    password: admin
    virtual-host: /
  redis:
    host: 10.45.50.241
ly:
  sms:
    accessKeyId: LTAIak6fEo1Fzdnl # 自己的accessKeyId
    accessKeySecret: N26r0rV3KjKZBfIIA1qjwmyVwX3S7 # 自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_163052577 # 模板名称 sms参数均少一位，ID密码请去阿里云官方申请
