server:
  port: 8083
logging:
  level:
    root: INFO
    com:
      leyou: DEBUG
  file: ./logs/search.log
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 10.45.50.241:9200
  jackson:
      default-property-inclusion: non_null # 配置json处理时忽略空值
  rabbitmq:
    host: 10.45.50.241
    username: admin
    password: admin
    virtual-host: /
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
