server:
  port: 10011
spring:
  application:
    name: leyou-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huhua1990/leyou-config.git
  rabbitmq:
    host: 10.45.50.241
    username: admin
    password: admin
    virtual-host: /


management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
