server:
  port: 10010
spring:
  application:
    name: api-gateway
logging:
  level:
    root: INFO
    com:
      leyou: DEBUG
  file: ./logs/gateway.log

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka #Eureka服务器的地址
    registry-fetch-interval-seconds: 5 #客户端拉取服务注册信息间隔
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 5
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 5
zuul:
  prefix: /api # 添加路由前缀
  routes:
    item-service: /item/**
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order/**
    seckill-service: /seckill/**
    comments-service: /review/**
    ignored-services:
      - upload-service # 忽略upload-service服务
  add-host-header: true #携带请求本身的head头信息
  retryable: true
  sensitive-headers: #匹配禁止使用的头信息，这里设置为null，否则set-cookie无效
#    upload-service: #/upload/**:不能这样写，网关捕获到upload之后页面的url只剩下/image，但是controller里面是/upload/image,所以不能去除upload的前缀
#      path: /upload/**
#      serviceId: upload-service
#      strip-prefix: false
ribbon:
  ConnectTimeout: 4000 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
leyou:
  jwt:
    #pubKeyPath: H:/javacode/idea/rsa/rsa.pub # 公钥地址
    pubKeyPath: /leyou/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
       /api/auth
       /api/search
       /api/user/register
       /api/user/check
       /api/user/code
       /api/item
