server:
  port: 8087
spring:
  application:
    name: auth-service
  zipkin:
    base-url: http://10.45.50.241:9411/
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    root: INFO
    com:
      leyou: DEBUG
  file: ./logs/auth.log
eureka:
  client:
    service-url:
      defaultZone: http://10.45.50.241:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 10.45.50.241
    instance-id: ${spring.application.name}:${server.port}
leyou:
  jwt:
    secret: ly@Login(Auth}*^31)&yun6%f3q2 # 登录校验的密钥
    #pubKeyPath: H:/javacode/idea/rsa/rsa.pub # 公钥地址
    #priKeyPath: H:/javacode/idea/rsa/rsa.pri # 私钥地址
    pubKeyPath: /leyou/rsa/rsa.pub # 公钥地址
    priKeyPath: /leyou/rsa/rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN
    cookieMaxAge: 30


ribbon:
  ConnectTimeout: 4000 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true
