server:
  port: 8086
logging:
  level:
    root: INFO
    com:
      leyou: DEBUG
  file: ./logs/sms.log
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 10.45.50.241
    username: admin
    password: admin
    virtual-host: /
  redis:
    host: 10.45.50.241
leyou:
  sms:
    accessKeyId: LTAIc259TULYzaS7 # 自己的accessKeyId
    accessKeySecret: 1uh79I1UAmwQ4YWsSmOgxw7JEBGA0v # 自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_148614415 # 模板名称 sms参数均少一位，ID密码请去阿里云官方申请
