server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
      url: jdbc:mysql://10.45.50.241:3306/leyou
      username: leyou
      password: leyou
      driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    root: INFO
    com:
      leyou: DEBUG
  file: ./logs/order.log
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
mybatis:
  type-aliases-package: com.leyou.order.pojo
leyou:
  jwt:
    #pubKeyPath: H:/javacode/idea/rsa/rsa.pub # 公钥地址
    pubKeyPath: /leyou/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  worker:
    workerId: 1
    dataCenterId: 1
  pay:
    appId: wx8397f8696b538317
    mchId: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    httpConnectTimeoutMs: 1000
    httpReadTimeoutMs: 8000
    notifyUrl: http://tzatwh.natappfree.cc/notify/pay
    connectTimeoutMs: 5000
    readTimeoutMs: 10000
