server:
  port: 8085
logging:
  level:
    root: INFO
    com:
      leyou: DEBUG
  file: ./logs/user.log
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://10.45.50.241:3306/leyou
    username: leyou
    password: leyou
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 10.45.50.241
    username: admin
    password: admin
    virtual-host: /
  redis:
    host: 10.45.50.241
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
#    instance-id: ${eureka.instance.ip-address}.${server.port}
#    lease-renewal-interval-in-seconds: 3
#    lease-expiration-duration-in-seconds: 10
mybatis:
  type-aliases-package: com.leyou.user.pojo #指定POJO扫描包来让mybatis自动扫描到自定义POJO，interface中的pojo
